port: 9999
https: true
proxies:
  - router_path: "/v2"
    target_url: "https://httpbin.org/anything/v2"
  - router_path: "/v1"
    target_url: "https://httpbin.org/anything/v1"
  - router_path: "/"
    target_url: "https://httpbin.org/anything/default"
